### PR TITLE
Fix "No entities found" error

### PR DESCRIPTION
**Pull request by phlegx**
Fixes:

https://github.com/voormedia/rails-erd/issues/45
https://github.com/voormedia/rails-erd/issues/42

thanks to espinosa to find the error.

Not sure if this breakes other things though.

### CODE REVIEW

**Comment by kerrizor** [comment]
Unfortunately this breaks tests and examples horribly. Closing for now, but would love to know if the issue this was addressing is still plaguing users (without a test its hard to prove) :(

**Comment by andynu** [comment]
The issue does persist. For my purposes I've made this change locally.

**Comment by kerrizor** [comment]
@andynu - can you provide actual repo steps or a test suite? It'd help us solve this once and for all.

**Comment by andynu** [comment]
Fortunately it seems to happen for me in a simple new project as well, so yes here are repro steps. I think I've included the relevant details. Please let me know if you need more.

		ruby --version 
		ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

		rails --version
		Rails 4.2.1

		rails new erd1
		cd erd1
		bin/rails g scaffold User name:string
		edit Gemfile add:
		  gem 'rails-erd'
		bundle

rake erd --trace

		** Invoke erd (first_time)                                                              
		** Invoke erd:generate (first_time)                                            
		** Invoke erd:options (first_time)
		** Execute erd:options
		** Invoke erd:load_models (first_time)
		** Execute erd:load_models
		Loading application environment...                                             
		** Invoke environment (first_time)
		** Execute environment
		Loading code in search of Active Record models...
		** Execute erd:generate
		Generating Entity-Relationship Diagram for 1 models...
		rake aborted!
		No entities found; create your models first!
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:159:in `block in filtered_entities'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:158:in `tap'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:158:in `filtered_entities'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:128:in `generate'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:119:in `create'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/diagram.rb:74:in `create'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rails-erd-1.3.1/lib/rails_erd/tasks.rake:41:in `block (2 levels) in <top (required)>'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:201:in `block in invoke_prerequisites'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `each'                                                                 
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:199:in `invoke_prerequisites'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:178:in `block in invoke_with_call_chain'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'                                                   
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'                                                          
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
		/home/andy/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
		/home/andy/.rbenv/versions/2.1.5/bin/rake:23:in `load'
		/home/andy/.rbenv/versions/2.1.5/bin/rake:23:in `<main>'
		Tasks: TOP => erd => erd:generate

cat ~/.erdconfig

		attributes:
		  - content
		  - foreign_key
		  - inheritance
		disconnected: true
		filename: doc/erd
		filetype: png
		indirect: true
		inheritance: false
		markup: true
		notation: bachman # simple bachman
		orientation: horizontal # vertical horizontal
		polymorphism: false
		sort: true
		warn: true
		#title: sample title
		only: null
		prepend_primary: false
		exclude: ActiveRecord::SessionStore::Session
		# vim: ft=yaml

cat Gemfile.lock

		GEM                                                                             
		  remote: https://rubygems.org/                                                 
		  specs:                                                                        
		    actionmailer (4.2.1)                                                        
		      actionpack (= 4.2.1)                                                      
		      actionview (= 4.2.1)                                                      
		      activejob (= 4.2.1)                                                       
		      mail (~> 2.5, >= 2.5.4)                                                   
		      rails-dom-testing (~> 1.0, >= 1.0.5)                                      
		    actionpack (4.2.1)                                                          
		      actionview (= 4.2.1)                                                      
		      activesupport (= 4.2.1)                                                   
		      rack (~> 1.6)                                                             
		      rack-test (~> 0.6.2)                                                      
		      rails-dom-testing (~> 1.0, >= 1.0.5)                                      
		      rails-html-sanitizer (~> 1.0, >= 1.0.1)                                   
		    actionview (4.2.1)                                                          
		      activesupport (= 4.2.1)                                                   
		      builder (~> 3.1)                                                          
		      erubis (~> 2.7.0)                                                         
		      rails-dom-testing (~> 1.0, >= 1.0.5)                                      
		      rails-html-sanitizer (~> 1.0, >= 1.0.1)                                   
		    activejob (4.2.1)                                                           
		      activesupport (= 4.2.1)                                                   
		      globalid (>= 0.3.0)                                                       
		    activemodel (4.2.1)                                                         
		      activesupport (= 4.2.1)                                                   
		      builder (~> 3.1)                                                          
		    activerecord (4.2.1)                                                        
		      activemodel (= 4.2.1)                                                     
		      activesupport (= 4.2.1)                                                   
		      arel (~> 6.0)                                                             
		    activesupport (4.2.1)                                                       
		      i18n (~> 0.7)                                                             
		      json (~> 1.7, >= 1.7.7)                                                   
		      minitest (~> 5.1)                                                         
		      thread_safe (~> 0.3, >= 0.3.4)                                            
		      tzinfo (~> 1.1)                                                           
		    arel (6.0.0)                                                                
		    binding_of_caller (0.7.2)                                                   
		      debug_inspector (>= 0.0.1)                                                
		    builder (3.2.2)                                                             
		    byebug (4.0.5)                                                              
		      columnize (= 0.9.0)                                                       
		    choice (0.1.7)                                                              
		    coffee-rails (4.1.0)                                                        
		      coffee-script (>= 2.2.0)                                                  
		      railties (>= 4.0.0, < 5.0)                                                
		    coffee-script (2.4.1)                                                       
		      coffee-script-source                                                      
		      execjs                                                                    
		    coffee-script-source (1.9.1)                                                
		    columnize (0.9.0)                                                           
		    debug_inspector (0.0.2)                                                     
		    erubis (2.7.0)                                                              
		    execjs (2.5.2)                                                              
		    globalid (0.3.5)                                                            
		      activesupport (>= 4.1.0)                                                  
		    hike (1.2.3)                                                                
		    i18n (0.7.0)                                                                
		    jbuilder (2.2.13)                                                           
		      activesupport (>= 3.0.0, < 5)                                             
		      multi_json (~> 1.2)                                          
		    jquery-rails (4.0.3)                                                        
		      rails-dom-testing (~> 1.0)                                                
		      railties (>= 4.2.0)                                                       
		      thor (>= 0.14, < 2.0)                                                     
		    json (1.8.2)                                                                
		    loofah (2.0.1)                                                              
		      nokogiri (>= 1.5.9)                                                       
		    mail (2.6.3)                                                                
		      mime-types (>= 1.16, < 3)                                                 
		    mime-types (2.4.3)                                                          
		    mini_portile (0.6.2)                                                        
		    minitest (5.5.1)                                                            
		    multi_json (1.11.0)                                                         
		    nokogiri (1.6.6.2)                                                          
		      mini_portile (~> 0.6.0)                                                   
		    rack (1.6.0)                                                                
		    rack-test (0.6.3)                                                           
		      rack (>= 1.0)                                                             
		    rails (4.2.1)                                                               
		      actionmailer (= 4.2.1)                                                    
		      actionpack (= 4.2.1)                                                      
		      actionview (= 4.2.1)                                                      
		      activejob (= 4.2.1)                                                       
		      activemodel (= 4.2.1)                                                     
		      activerecord (= 4.2.1)                                                    
		      activesupport (= 4.2.1)                                                   
		      bundler (>= 1.3.0, < 2.0)                                                 
		      railties (= 4.2.1)                                                        
		      sprockets-rails                                                           
		    rails-deprecated_sanitizer (1.0.3)                                          
		      activesupport (>= 4.2.0.alpha)                                            
		    rails-dom-testing (1.0.6)                                                   
		      activesupport (>= 4.2.0.beta, < 5.0)                                      
		      nokogiri (~> 1.6.0)                                                       
		      rails-deprecated_sanitizer (>= 1.0.1)                                     
		    rails-erd (1.3.1)                                                           
		      activerecord (>= 3.2)                                                     
		      activesupport (>= 3.2)                                                    
		      choice (~> 0.1.6)                                                         
		      ruby-graphviz (~> 1.0.4)                                                  
		    rails-html-sanitizer (1.0.2)                                                
		      loofah (~> 2.0)                                                           
		    railties (4.2.1)                                                            
		      actionpack (= 4.2.1)                                                      
		      activesupport (= 4.2.1)                                                   
		      rake (>= 0.8.7)                                                           
		      thor (>= 0.18.1, < 2.0)                                                   
		    rake (10.4.2)                                                               
		    rdoc (4.2.0)                                                                
		      json (~> 1.4)                                                             
		    ruby-graphviz (1.0.9)                                                       
		    sass (3.4.13)                                                               
		    sass-rails (5.0.3)                                                          
		      railties (>= 4.0.0, < 5.0)                                                
		      sass (~> 3.1)                                                             
		      sprockets (>= 2.8, < 4.0)                                                 
		      sprockets-rails (>= 2.0, < 4.0)                                           
		      tilt (~> 1.1)                                                             
		    sdoc (0.4.1)                                                                
		      json (~> 1.7, >= 1.7.7)                                                   
		      rdoc (~> 4.0)                                                             
		    spring (1.3.4)                                                              
		    sprockets (2.12.3)                                                          
		      hike (~> 1.2)                                                             
		      multi_json (~> 1.0)                                                       
		      rack (~> 1.0)                                        
		      tilt (~> 1.1, != 1.3.0)                                                   
		    sprockets-rails (2.2.4)                                                     
		      actionpack (>= 3.0)                                                       
		      activesupport (>= 3.0)                                                    
		      sprockets (>= 2.8, < 4.0)                                                 
		    sqlite3 (1.3.10)                                                            
		    thor (0.19.1)                                                               
		    thread_safe (0.3.5)                                                         
		    tilt (1.4.1)                                                                
		    turbolinks (2.5.3)                                                          
		      coffee-rails                                                              
		    tzinfo (1.2.2)                                                              
		      thread_safe (~> 0.1)                                                      
		    uglifier (2.7.1)                                                            
		      execjs (>= 0.3.0)                                                         
		      json (>= 1.8.0)                                                           
		    web-console (2.1.2)                                                         
		      activemodel (>= 4.0)                                                      
		      binding_of_caller (>= 0.7.2)                                              
		      railties (>= 4.0)                                                         
		      sprockets-rails (>= 2.0, < 4.0)                                           
				                                                                
		PLATFORMS                                                                       
		  ruby                                                                          
				                                                                
		DEPENDENCIES                                                                    
		  byebug                                                                        
		  coffee-rails (~> 4.1.0)                                                       
		  jbuilder (~> 2.0)                                                             
		  jquery-rails                                                                  
		  rails (= 4.2.1)                                                               
		  rails-erd                                                                     
		  sass-rails (~> 5.0)                                                           
		  sdoc (~> 0.4.0)                                                               
		  spring                                                                        
		  sqlite3                                                                       
		  turbolinks                                                                    
		  uglifier (>= 1.3.0)                                                           
		  web-console (~> 2.0)

**Comment by andynu** [comment]
Ah! So the example erdconfig listed on https://github.com/voormedia/rails-erd includes the 'only: nil' line. When I remove this things work fine. When I include that the options.only is resolving to an empty array rather than nil, so the truthy evaluation on diagram.rb:154 returns true instead of false, which explains why it thinks there are no classes.

**Comment by hooverlunch** [comment]
This worked for me too. The example config should be amended. Would submit PR but so swamped right now!

**Comment by andynu** [comment]
This might be better fixed deeper down. This PR will help first time users, but people may still stumble into this misconfiguration.

**Pull request closed without merging**
