### PR TITLE
Drop support for Rails 3.2 -> 4.0, Run tests for Rails 5.1 + 5.2

### PR DESCRIPTION
**Pull request by mathieujobin**
I removed the old rubies and added rails 5.1 and 5.2

strangely, I get a pass status for rails 5.1 and 5.2 but not for rails 4.2 and 5.0 ?!? and it does not look ruby related. so I'm not sure.

### CODE REVIEW

**Comment by kerrizor** [comment]
Hi, and thanks for the PR! Apologies on not responding sooner; my workflow for being notified of new issues broke such that I received _some_ notifications, but not all, and unfortunately yours was one I missed.

If you have the time, could you rebase and resubmit? I recently merged fixes for minitest that may help clear up your test failures.

That said.. I'm not 100% sure I want to be quite this aggressive in dropping support for old(er) Rubies. I'd like to drop Rails 3.2 and Ruby 1.9.3, but I'd like to do so in the context of a version release so there's a clear line of support for those still on older versions.

**Comment by mathieujobin** [comment]
@kerrizor my turn to be sorry for not looking at this earlier..

since the Rails core team no longer support those old version, i think it makes sense to remove them.
should someone want to use this gem with older version of rails, they can use the last compatible version.

**Comment by kerrizor** [comment]
@mathieujobin I find myself agreeing with you. Let's see if I can get a clean test run.

**Comment by kerrizor** [comment]
@mathieujobin just a heads up, I'm going to cherrypick your original commit over to a new PR once I isolate and fix the test failures; I want to isolate the version bump into its own commit, just to keep things easier to track (thanks for writing the code for it, though!)

**Comment by mathieujobin** [comment]
no problem @kerrizor 

let me know if you want me to rebase or take out any bits off this PR

**Comment by kerrizor** [comment]
Closing in favor of #306 -- thank you again for the contribution!!

**Pull request closed without merging**
