### PR TITLE
Issues/227

### PR DESCRIPTION
**Pull request by cobbr2**
Tested with Ruby 1.9.3-p551, 2.1.5 and 2.3.1 .  Gave  up on making my new test helper completely compatible with `create_model`.

### CODE REVIEW

**Comment by cobbr2** [comment]
Not ready yet, according to Travis. Maybe later in the week.

**Comment by kerrizor** [comment]
Actually, looks like that was just a flaky test (I've found that **for this gem** Travis tests that fail are sometimes just an issue with how Travis does server instance caching, and restarting the test after a min or two will push it green (nearly 100% true when its just one or two failing test scenarios)

**Comment by kerrizor** [comment]
(So I guess I'm saying, reopen this and I'll likely merge it)

**Comment by cobbr2** [comment]
Thanks!

**Comment by kerrizor** [comment]
#227

**Pull request merged**
