### PR TITLE
Fix for https://github.com/voormedia/rails-erd/issues/381

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by simi** [comment]
:thinking: Is this not covered by tests?

**Comment by kerrizor** [comment]
:grumble:

I just realized that Travis integration wasn’t firing. I’m severely offline
the next 48 hours, will circle back on Thursday and get a patch release
out. Thanks for catching this.

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by kerrizor** [comment]
> Hi there! Any news?

Yeah, I just got back from travels.. I forgot that I can't actually rebase your remote branch (SIGH!) so I had to fiddle with things in another MR to get the checks running. Looks ✅

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
