### PR TITLE
make RailsERD Engine

### PR DESCRIPTION
**Pull request by mitsuru**
make RailsERD Engine, `auto generate diagram` feature now working.

### CODE REVIEW

**Comment by kerrizor** [comment]
Thank you!

**Comment by bf4** [comment]
heh, this broke our production deploy in a db:migrate, 

> Verify that Graphviz is installed and in your path, or use filetype=dot.

> StandardError: GraphViz not installed or dot not in PATH. Install GraphViz or use the 'path' option

well, oops on us for having it on in production, but pretty unexpected

```diff
-    rails-erd (1.4.2)
+    rails-erd (1.4.5)
```

**Comment by kerrizor** [comment]
@bf4 I'm rolling this back shortly.. and my apologies 😢

**Comment by bf4** [comment]
Should probably follow a pattern like the annotate gem.

Anyhow, still weird that it bit us.

B mobile phone

**Comment by mitsuru** [comment]
https://github.com/voormedia/rails-erd/pull/176#issuecomment-182111984
My environment is as follows .

Gemfile
```
group :development do
   gem 'rails-erd'
end
```

**Pull request merged**
