### PR TITLE
Removed restriction that allowed to exclude only models from a diagram

### PR DESCRIPTION
**Pull request by bpohoriletz**
Especially helpful when having polymorphic/indirect relationships

### CODE REVIEW

**Comment by kerrizor** [comment]
Hi! Thanks for submitting this, and thank you for your patience.. this looks good, but now I'm nervous that we don't have a test for this (but then, this blob of code has been a near constant source of pain for me..) How confident can we be that we're not removing functionality here?

**Comment by bpohoriletz** [comment]
@kerrizor when do you plan to release **v1.6.0**? I'd be happy to add tests for this.

**Comment by kerrizor** [comment]
@bpohoriletz It'll be a few weeks at least, so plenty of time if its something you'd like to add!

**Comment by bpohoriletz** [comment]
Hello,
I've added a test for the new exclusion rule, I can't run test for rake tasks in my local.
I'm quite sure that it does not remove any functionality for two reasons:
1. Building a graph will work fine after the change. The code ` draw_node entity.name, entity_options(entity, attributes) ` requires only name and all entities have it
2. Before the change one could not remove entities that were not models from the graph, so the change makes exclusion more restrictive if needed

Thanks!

**Comment by kerrizor** [comment]
Hi, and thanks for the PR! Apologies on not responding sooner; my workflow for being notified of new issues broke such that I received _some_ notifications, but not all, and unfortunately yours was one I missed.

If you have the time, could you rebase and resubmit? I recently merged fixes for minitest that may help clear up your test failures.

**Comment by bpohoriletz** [comment]
@kerrizor no problem at all, thank you for all your work!

**Pull request merged**
