### PR TITLE
Handle paper_trail's custom version classes.

### PR DESCRIPTION
**Pull request by inclooder**
Fix for #303 
Handle paper_trail's custom version classes.

### CODE REVIEW

**Comment by kerrizor** [comment]
Hi, and thanks for the PR! Apologies on not responding sooner; my workflow for being notified of new issues broke such that I received _some_ notifications, but not all, and unfortunately yours was one I missed.

If you have the time, could you rebase and resubmit? I recently merged fixes for minitest that may help clear up your test failures.

**Comment by inclooder** [comment]
@kerrizor thank you for your time. I've rebased the branch but the master is failing so this one will fail too :(

**Comment by kerrizor** [comment]
@inclooder Hmmm.. looks like an `apt-get` hiccup on Travis.. I've rerun the build for <master> and it does show green now.

**Comment by kerrizor** [comment]
@inclooder I had so many things to do with rebasing and merging that I went ahead and opened a new branch for this PR at #325 (don't worry, you'll still get credit! 😉) Thanks again for your contribution and your patience!

**Pull request closed without merging**
